### PR TITLE
Initial version of logstash-mixin-zeromq

### PR DESCRIPTION
**Pull request by breml**
Made PR based on https://github.com/breml/logstash-util-zeromq as suggested by @suyograo in https://github.com/elastic/logstash/issues/4813

### CODE REVIEW

**Comment by breml** [comment]
@logstash-core, @suyograo, @avishai-ish-shalom With the latest release of logstash beeing published, I would love to see some progress on this one.
This one is blocking progress on the following issues / PR:
* https://github.com/logstash-plugins/logstash-input-zeromq/pull/18 (https://github.com/logstash-plugins/logstash-input-zeromq/issues/17)
* https://github.com/logstash-plugins/logstash-output-zeromq/pull/13 (https://github.com/logstash-plugins/logstash-output-zeromq/issues/12)
* https://github.com/elastic/logstash/issues/4813

**Comment by avishai-ish-shalom** [comment]
@suyograo, i believe only you can merge this at the moment. also consider giving me write access to this repo.

**Comment by acchen97** [comment]
@avishai-ish-shalom I've gave you write access to this repo.

**Comment by breml** [comment]
@avishai-ish-shalom thanks, how do we precede?

**Comment by avishai-ish-shalom** [comment]
I've updated logstash-filter-zeromq, logstash-output-zeromq and logstash-input-zeromq to use this mixin. Please review them and lmk. If I don't see any issues in a few day i'll release the new versions (2.1.0)

**Comment by breml** [comment]
LGTM, as far as I can tell until now.

**Pull request merged**
