### PR TITLE
fix build and bring plugin to current travis standards

### PR DESCRIPTION
**Pull request by jakelandis**
Honestly not sure why the logger changes are needed, it seems like the old code should have worked (and it did for a long time), but running without this 'fix' fails with the following error.

```
     Failure/Error: impl.logger = tracer
     
     NoMethodError:
       undefined method `logger=' for #<Dummy:0x270d5060>
       Did you mean?  logger
```
The other changes are copy paste from other more updated projects.

### CODE REVIEW

**Review by yaauie — APPROVED** [review]
@jakelandis _tl;dr: LGTM_

***

I'm not really sure how this ever worked -- neither `LogStash::Inputs::Base` nor `LogStash::PluginMixins::ZeroMq` provide a `logger=` in recent history (checked LS 5.5+).

It is a little weird that this mixin (and its consumers) uses the `@logger` instance variable directly instead of the `LogStash::Util::Loggable#logger` that is part of the input/output/plugins public APIs. If we used the public APIs, we could trivially hook and mock without reaching into internals.

That said, this mixin's _consumers_ also use `@logger` directly, and fixing them is a bit out of scope for this PR.

**Comment by jakelandis** [comment]
@yaauie  - _tld;dr_ : Thanks!

---------
`LogStash::Inputs::Base` includes `LogStash::Util::Loggable` which defines a `logger` method in the self scope of the plugin. 

The `logger` method _should_ simply return a `LogStash::Logging::Logger` ...which via debugging I confirmed it actually DOES.  The code here is simply trying to assign that `LogStash::Logging::Logger` reference (which is actually `@logger`) to the mock. 

What I don't understand is _why_ it is trying call `logger=` instead of simply doing an assignment.  I also don't understand what changed that caused this change in behavior.  This type of issue makes me question my competency or sanity  :) 

Given it is just a test with an easy work around, didn't want to go too far down that rabbit hole.

**Comment by yaauie** [comment]
@jakelandis following up post-merge to attempt to add clarity

> What I don't understand is why it is trying call logger= instead of simply doing an assignment.

In Ruby, instance variables are _always_ object-internal; they cannot be read or written to from the outside of the object. Getters and setters must be defined to provide access to them.

By convention, getters are methods that are just the name of the variable, and setters are methods that are the name of the variable followed by an `=` that take a single argument; macros like `attr_writer` and `attr_accessor` define these methods under the covers (the following are equivalent):

~~~ ruby
class Foo
  attr_accessor :bar
end
~~~
~~~ ruby
class Foo
  attr_reader :bar
  attr_writer :bar
end
~~~
~~~ ruby
class Foo
  def bar
    @bar
  end
  def bar=(bar)
    @bar = bar
  end
end
~~~

> The logger method should simply return a LogStash::Logging::Logger ...which via debugging I confirmed it actually DOES. The code here is simply trying to assign that LogStash::Logging::Logger reference (which is actually @logger) to the mock.

`LogStash::Util::Loggable`, which is mixed into the various base classes for inputs, filters, and outputs, defines a set of methods for acquiring an appropriate `Logger`; the fact that this logger is memoised in the `@logger` instance variable is an _internal detail_ to `LogStash::Util::Loggable`, so directly accessing `@logger` is both foolish and fragile.

If consumers were well-behaved, and used `LogStash::Util::Loggable#logger` to acquire their logger instead of directly from the instance variable, we would be able to simply stub out the `logger` method to return our tracer.

**Comment by jakelandis** [comment]
> instance variables are always object-internal;

In this case we playing games with the self object so the `@logger` that is returned from the `logger` method i _think_ should belong to the plugin class itself.   

FWIW, I tried to explicitly include ```LogStash::Util::Loggable``` into the Dummy plugin class, as well as explicitly adding attribute accessors, but both had the same error. 

What is odd thing is that this code worked prior July, and I checked the relevant histories and nothing relevant that i could find changed.

**Pull request closed without merging**
