### PR TITLE
Dependency logstash-core-plugin-api to >= 1.60 <= 5.99

### PR DESCRIPTION
**Pull request by joostmeijles**
To be compatible with ELK 5.x, upgrading the maximum version to 5.99.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @joostmeijles, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-mixin-zeromq/pull/9.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by joostmeijles** [comment]
Done.

Op di 18 apr. 2017 om 13:07 schreef Karel Minarik <notifications@github.com>

**Comment by jsvd** [comment]
Hi, to all commenting here, the current problem with releasing this gem and making it work with logstash 5.x isn't the depending on `logstash-core-plugin-api` but the fact that the gem is owned by someone else so we can't publish it to rubygems.

to further explain, the `logstash-core-plugin-api` is versioned differently than the rest of the stack since it represents the contract between logstash core and the plugins. Even with the recently released logstash 5.3.0, the [logstash-core-plugin-api version is still at 2.1.12](https://github.com/elastic/logstash/blob/v5.3.0/versions.yml)

Since we can't publish this gem to rubygems.org due to [Avisai being the only owner](https://rubygems.org/api/v1/gems/logstash-mixin-zeromq/owners.json) of the gem, I started a new effort to have all zeromq plugins [under a single repository](https://github.com/logstash-plugins/logstash-integration-zeromq) and under a single .gem

I hope to release this soon, but there's no target at the moment.

**Comment by tfgm-bud** [comment]
@jsvd +1 on releasing soon!

**Comment by joostmeijles** [comment]
@jsvd understood and will close this PR.

I was confused with the released [v4.0](https://github.com/logstash-plugins/logstash-mixin-zeromq/releases/tag/v4.0.0) version and the current repository version of [v3.0.1](https://github.com/logstash-plugins/logstash-mixin-zeromq/blob/master/logstash-mixin-zeromq.gemspec#L4) in which the dependency was changed in your [commit](https://github.com/logstash-plugins/logstash-mixin-zeromq/commit/7c39ea072534e68f90a2e81b3c0ca3b0c4c4a17f#diff-ae8aa6d1d142fd5290b2549e481c720e).

**Pull request closed without merging**
